### ISSUE TITLE
IT WORKS!!! BUT encrypted_private_key needs cracked

### ISSUE THREAD

**Issue by Starblue0** [jimtje/walletlib#71]
I finally got my encrypted private key from my wallet.dat, Here is the thing I forgot the password and it's been years and i mean years since i accessed my wallet. 
 
How would i go about cracking my encrypted private key.  example shown below
` {
            "encrypted_private_key": "bc2e8d65b05505d35efb45c771a0ef05e86f06df6207da05446859a1984801314d4996f435666a5c583947d17ee0638e",
            "public_key": "13FEuaQUxqUmCsDbWqdai7WtDkqpyt8jzo"
        }
`

**Comment by jimtje** [comment]
Hey there. Unfortunately cracking the key is kind of a whole separate process that I don't plan on adding to the library because other, much smarter and dedicated folks have worked on it far more diligently already. Right now, the encrypted_private_key is more or less a hash for comparison purposes here. I don't have any formal training in programming and so I have no idea how to rig up testing without using an actual used wallet, which is a security risk, imo, since I do have formal legal training and experience and know what parts of the blockchain analysis technology is admissible and what isn't. All that is to say, sorry, the individual encrypted_private_key isn't really of much use to anyone except to confirm that it's a wallet with keys in it, and it's for the best that this part of the output is used for what it's currently used for.

In any case, wallet.dat files that are in the BerkeleyDB format mostly only require the master key to be cracked. You can extract that master key with JohnTheRipper with https://github.com/openwall/john with the bitcoin2john.py file under /run, and you can use anything from hashcat to... paying to use someone else's ridiculously tricked out rig to run hashcat via vast.ai to... just paying someone to crack it (I don't know any more efficient way that doesn't expose your actual password and wallet together to a third party, but this method does not expose your actual private keys). btcrecover is also an option if you can at least guess - or have some semblance of an idea - what your password might be. Best of luck, and hopefully Christmas comes early for you this year. Cheers.
